### ISSUE TITLE
Edit README for each repo with appropriate installation instructions

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#12]
#### TODO:
- [ ] - Update Node Readme
- [ ] - Validate Python Readme
- [ ] - Edit issue tracking readme to point to our repo forks
